apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: mysql-1
  namespace: everest
spec:
  engine:
    replicas: 1
    resources:
      cpu: "1"
      memory: 2G
    storage:
      class: standard-rwo
      size: 25G
    type: pxc
    userSecretsName: everest-secrets-mysql
    version: 8.0.32-24.2
  proxy:
    expose:
      type: internal
    replicas: 1
    type: haproxy
---
