apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: my-cool-cluster
  namespace: my-special-place
spec:
  allowUnsafeConfiguration: true
  backup:
    enabled: false
    pitr:
      enabled: false
  engine:
    replicas: 1
    resources:
      cpu: "1"
      memory: 2G
    storage:
      class: standard-rwo
      size: 25G
    type: pxc
    userSecretsName: everest-secrets-mysql-iuf
    version: 8.0.32-24.2
  proxy:
    expose:
      type: internal
    replicas: 1
    resources:
      cpu: "0"
      memory: "0"
    type: haproxy
