apiVersion: everest.percona.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3
  namespace: everest-system
spec:
  allowedNamespaces:
  - n1
  bucket: mayank-everest-test
  credentialsSecretName: s3
  description: s3
  endpointURL: https://s3.us-west-2.amazonaws.com
  forcePathStyle: false
  region: us-west-2
  type: s3
  verifyTLS: true
