---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3
  namespace: everest-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCJrRkJOOywWWhCSOPqlCiAuDx5zR1gCSMnf7N6IZXWxOkIaBZ9gIl95up40xKYgmkF6A0lWCEU1PEJfSxWPUX7ptmdOuZwzxFTHpzszaU9AjMvP/Yf8Im/JAGBxOLXbgMUtjsuEdADth/zADGmYq7YHKIDuk9BpzgTORPWiq9WkFWc6FhOE59D7HK5o1tyaZUcVE0g2jlj8Oi70HpfjHxJXgcnsHmw0D95VbsYE4JgY+PvLeEXFvCvRDSWvf466CoT25BLblg0Uq8TQPGVpyzc9fI6KJmwViSTpMSm8p2FMfk8yh5weYnbP3bUvDCHFP+9IABeqsuTdkfUuSJiqnkAZZkA31qYNgMZ9Xl+KBf448crgy1K8/10hQG5g6wQu31zVE8hKoPVIhhE18Z4b4CGAGNE+jwd8J6z8pIy7P296QBZdWdSwpLgJ03oESc1cdww+4tTBaNgufJ+5UUWQUaBvPvx2TcIBYFcwLTQ1eVsFkjBcIrJcbvqWsgPoo6tG1+XStEwUGneH0c+uxyZGXzxdwAkLBllGlf8SLFCYSJBpUTQHis3p3MJKdGxivkSPIj+0ubzVFmzP1mWtC+4J9ngnABJb+pA9VG3NJ1p3g5xfix+FYZmIlK3Ge0f6+hrt0hUV6o3ra9gzmA+sbn5fqFvgBxptldvrxeA/n9EO2/kpalzfBUETfGWbxnSn0pD6S/QYSDGsyxQzui1pRxCTJLqvIbZlw==
    AWS_SECRET_ACCESS_KEY: AgAz6ILolvingdpoFdVSumwR9Pxmmmi9YNgDxbyEC5bEnuVLB0dq0Om94T5zRJbLSQUivq3PfBH2FasZixAhKuNf9xJAEwjuZobpTGp7NiExSX2jfO22rFMY/jbqqSf9pud5grBgyjdITPuwpwavLwned7wY1NMMfwslS6prRPVyY97sKbAoVhHnDFlAet327Nz1hXPJ4xtXNXmpYZvv8kbVdAlDqLjK0NDa9eBoV5FkWeXVSVWvNhiIUhtEGo/bnnD7/lB6T+KoeDWY7H6Dbx8PxEKIk4bfTdP5uAymXR+ebvI2hxjl3d1gFNuoUQb7rNumgnyG6wZ6xPT4dQ0k6/GGnNfIDqcIDkhQq4ZUeKwrVdi8ITF0gJiCOYuDcvUW2ZhVMexhAWCraqIRSjRanksP57u5RmNVfGaWA0Hcb42M05JChHcH6o13yUO2RdOtkvIIkAKPDIjbTpV87o5cBffB6c03EVYc0oq8Sl1WpDVPbFZez55MFYMypU/soLa+Tsr5DgSr6B8nO2WwmPWn6ftT56jmPNUkslakSv0FvuNhq1gMF3nvdWa6skmw54sXoLTeNq2pMMVcIK000Mod9emfnLepdwywDA+R4gRK+HHYq66gx0bCBp+HP0DeuxZ5JB3B5Q4+dv/4dDIlJc7+Dd5dyarlvzane70ZbRKyBS/4puoNs6j6jQuqXWqz7dIc2EMxX+XcDYIQKQb19ytZloQzFzTC3/WlB2Wvc7VjslH/tJysFwbsDo/l
  template:
    metadata:
      creationTimestamp: null
      name: s3
      namespace: everest-system
    type: Opaque
