---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3
  namespace: everest-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBD+R/t8pwrSS/OYuLSIWgU7ahdh/GlSo9xNnS0QmRmemr8RYDWWCESmmqomQjD7ugn7sAByWykwd3kg1pJkB/xp4KS5A8Pfv27pW7dhYHmlC2HjvWypD9a2n+IGSKL46oEIuRzdM6Y07PQDqEp7CVSw+0Pgtoy/7NoNYN0ZCycNj6VVneN1UP2S1KmXyQf5ADOJbhwkAJi2v+SBhTKaww4TgNb+yeeGrd5IksdRVMVfDwybVVhNrOq8n4FAj2WRTOvXv41Zhc3WullBrPTISyQg/u9pr4V92yb88uVZ0VoKS8eSeg2Ujc+tNAvlw+XeLvnTO8jXMY0DDWfv3CSfIgWSciDnLS53riUeIYNZkBaffpbvTCRTaKaBsU/uDStPYmlLkwgFms88QpviMBufHZYSzeAjFCuCLPAIe2kQASBXc1/cNeQfkCZtLLfe67CYP9qeKUKYT4kYGa6UD/Xt6lOY+wd2+Hfov4bV7c5cwpN0pnCXFgk8oB4w4DVP0Hdlcy2OWGnfiXgXvQA0jz0qZEU4yeC6MwiRoZsb1pwvukehRTVeeCeJ9Ozyh3llmkvhhiPoQ6p+9a1mVG8fAWkFP/ti/TPZcCnysrJVKSD6qaJsfXKD12HKHWlxiCxDlvYHhtvArViCkz7GPhgyhMwchTQNiE640IX0rFA68GsB2B14+MxodYuNTbwj3ffwQcFhtTGL2c3nEa9VDzGswAinG8=
    AWS_SECRET_ACCESS_KEY: AgA4EL7zvDS485AihyFUhq3tRcPH1yEhopOdpmina60+6iQRYfhimW++Kqy5zSFJfE4AbCIyet/Ld+d/vMbO3cgyS/cu/CokqqvljyQcuGBvUQ/kavLlL8k0cqyyyk916zdQR+qSl68XiFzCITfvFzhFWtQF8RqDH3ZZMoDbfvdDly5eVcPJ/lzZYXRKaxq2uyCNOyrWZyjVZr/P4f1QELkqNbhZ76mE+p0IdG9akjgsoUFjG41iPHE6c/MqoaGmJ31CHBRW7hS1pCBtRi2mRhiWdkvrvxVkh7PPHfu5ub0etoa+YoVUV7Oa7n+jXQhZxDcVN3NiZs47tog4z2lQCvpJgMTZwYKuIVd66MQOgZfUXl5Etv2YGVB3wt8V6hin4HV8Jp4cYemfhjP/zw94dNC7ciAD6vd1nRQa0gc/h/kVlzfO1V8jWdMu5ES4wEv4WCPBoy1lNPh/UXGx2y9OXgUECp+0HoaQKLQf3z12a2c+eTBsojJXscnMnnPXB3RhOgQKHJznEVJUAbz3y48zzqqFK5Cw6fhD+xr0Uxjiv6J39Bja9cx4lOjzUO0W94/2nB1YrWiwJ5ojFhkVSPMy6jogHHaVeX2y0240ZnLutU/IDR2b0X9bLmQ08AGefgKpOduqWytOkUt55gystuhFiwK20YMAZiuTAFr+OWhs+tbtLtaCKw36ySDSDFDvoX49Naqdofq0F6fa/i+drXGbZjCF4dhRHMUVzJzQC0zpbjU=
  template:
    metadata:
      creationTimestamp: null
      name: s3
      namespace: everest-system
---
apiVersion: everest.percona.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3
  namespace: everest-system
spec:
  allowedNamespaces:
  - dev
  bucket: mayank-everest-test
  credentialsSecretName: s3
  description: s3
  endpointURL: https://s3.us-west-2.amazonaws.com
  forcePathStyle: false
  region: us-west-2
  type: s3
  verifyTLS: true
---
