apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
metadata:
  name: mysql-cluster-1
  namespace: dev
spec:
  allowUnsafeConfiguration: true
  backup:
    enabled: true
    schedules:
    - backupStorageName: s3
      enabled: true
      name: backup-schedule-1
      schedule: 30 * * * *
  engine:
    replicas: 1
    resources:
      cpu: "1"
      memory: 2G
    storage:
      class: standard-rwo
      size: 25G
    type: pxc
    userSecretsName: everest-secrets-mysql
    version: 8.0.32-24.2
  monitoring:
    monitoringConfigName: pmm
  proxy:
    expose:
      type: internal
    replicas: 1
    type: haproxy
---
