---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pmm-secret
  namespace: default
spec:
  encryptedData:
    PMM_ADMIN_PASSWORD: AgB7O+QOkyiABKYQ56bYvtDO+l/Yp4ov/hsC8zlBVLkpXtTsXUy2Bd+WM6i5VNtsDAYdduqzo5/hWqB7nbTqUxBVkY+0YVOz0M/gtHWUhjtesItXHyRqA1LbWh5+gBzvvwYQSX056tdI5MGNT6e3ECNUouyLrcnfhOGir8aC0JCZ95aeBBpgwezmAqI1/IpVAifKpxhLGLM6wYV4z6nLNyBw9FBsl/FkUASKz1ukK7RpS17VE+aWjozIuSFeAqis4mK98pxWQCaMLd8unXMf345LyNUvSRi0CHXrNzo4NwARKVKI709CzxykI3rOmTpcWfkAgqRE1bMTV2FmppnyW0xS4oepgX+PQvAhau/28J5oLaygBzcDu98/MZPIyz/1DNchxCV5BwuaBFGmTfqXXhIpTAliEkIlwog7EOMcYvv2TEEy2hYNjJO62GUqx4jLkJGvNLEfsSKnjd6Pcsk3zArAvnp0ENFrfbpJyYQrRBtTgMUnGMx+1mGT/Kx3iFz3FyYxIe/LD6heHlGYqkQJgIOyu6NnIzKOkdfwtPv9nkmqdF+DB2Jjags+eXzAQ66ctpWgl+qKH6B0tS4YMvIs6lZ/n5ge0Mw2MC/tO5E394N7kXgfQjyYA4ImXWH+R8XpNiRUbRWW6lOVtDiaQ7xY6kS8l5/gJ6mAswDiWbT9ifvK4SCZahaq+ioYUpYSR/9SW7wrA/ZESw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: pmm
      name: pmm-secret
      namespace: default
    type: Opaque
