apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pmm
spec:
  project: default
  source:
    chart: pmm
    repoURL: https://percona.github.io/percona-helm-charts
    helm:
      releaseName: pmm
      valuesObject:
        secret:
          create: false
          name: pmm-secret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
